using System;
using TC.Domain.Entities;

namespace TC.Application.DTO.ColumnDTO
{
    public class ColumnAddRequest
    {
        public int BoardId { get; set; }
        public string Title { get; set; }
        public int SortOrder { get; set; } = 0;
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }

    public static class ColumnAddRequestExtensions
    {
        public static Column ToColumn(this ColumnAddRequest request) => new()
        {
            Id = 0, // Assuming Id is auto-generated by the database
            BoardId = request.BoardId,
            Title = request.Title,
            SortOrder = request.SortOrder,
            CreatedAt = request.CreatedAt
        };
    }
}