import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { QueryProvider } from "@/providers/query-provider";
import { MsalClientProvider } from "@/providers/msal-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-max antialiased`}>
            <body className="min-h-fit flex flex-col bg-linear-to-bl from-blue-200 via-purple-200 to-amber-200">
                <MsalClientProvider>
                    <QueryProvider>
                        <div className="min-h-screen">
                            {children}
                        </div>
                    </QueryProvider>
                </MsalClientProvider>
            </body>
        </html>
    );
}
