import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { QueryProvider } from "@/providers/query-provider";
import { msalConfig } from "@/authConfig";
import { PublicClientApplication } from "@azure/msal-browser";
import { MsalProvider } from "@azure/msal-react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const msalInstance = new PublicClientApplication(msalConfig);

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <MsalProvider instance={msalInstance}>
            <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-max antialiased`}>
                <body className="min-h-fit flex flex-col bg-linear-to-bl from-blue-200 via-purple-200 to-amber-200">
                    <QueryProvider>
                        <div className="min-h-screen">
                            {children}
                        </div>
                    </QueryProvider>
                </body>
            </html>
        </MsalProvider>
    );
}
