import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { QueryProvider } from "@/providers/query-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
                <body className="min-h-fit flex flex-col bg-linear-to-br from-blue-200 via-purple-200 to-amber-200">
                    <QueryProvider>
                        <div className="min-h-screen">
                            {children}
                        </div>
                    </QueryProvider>
                </body>
            </html>
        </ClerkProvider >
    );
}
