using System;
using System.ComponentModel.DataAnnotations;
using TC.Domain.Entities;

namespace TC.Application.DTO.BoardDTO
{
    public class BoardAddRequest
    {
        [Required]
        public string UserId { get; set; }

        [Required(ErrorMessage = "Title is required.")]
        public string Title { get; set; }

        public string Description { get; set; }

        public string Color { get; set; }

        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }

    public static class BoardAddRequestExtensions
    {
        public static Board ToBoard(this BoardAddRequest request) => new()
        {
            Id = 0, // Assuming Id is auto-generated by the database
            UserId = request.UserId,
            Title = request.Title,
            Description = request.Description,
            Color = request.Color,
            UpdatedAt = request.UpdatedAt,
            CreatedAt = request.CreatedAt
        };
    }
}